project:
  type: website

website:
  title: "My Personal Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Example Analysis"
        href: exampleanalysis.qmd
      - text: "Part 2"
        href: part2.qmd
        